//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyRentalManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MessageId { get; set; }
        public int FromUserId { get; set; }
        public int ToUserId { get; set; }
        public int ApartmentId { get; set; }
        public string Message1 { get; set; }
        public System.DateTime DateSent { get; set; }
        public int TypeId { get; set; }
        public bool IsRead { get; set; }
    
        public virtual Apartment Apartment { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual TypeMessage TypeMessage { get; set; }
    }
}
